Td 73 header refactoring
ReneNorth/Mosaic-courses-website pull request #102
Opened 2024-04-29 21:16 UTC by BRoman22

<h4>Изменения:</h4>
<p>• добавил константу роутинга и разнес ее по компонентам</p>
<p>• подготовил хедер к адаптиву</p>

[Задача](https://tessera-mosaic.atlassian.net/browse/TD-73)

2024-05-05 23:10 UTC, zigfrei commented
Большая просьба не делать столько изменений в одном пулреквесте, тяжело все это проверять, лучше завести новую задачу под определенное изменение и в ней его сделать. 
Не совсем понятно откуда в твоем пулреквесте изменения Юры? Надо уточнить из какой ветки Конфлюенс создает твою ветку? Надо чтобы из dev

#### Что необходимо исправить:
- Устранить горизонтальный скролл, в dev ветки такого скрола не было
- У иконки персоны установить параметр stroke-width на  1.5 или 2 например, просто сильно отличается размер обводки (вообще как будто есть отличие от макета в плане ширины обводки у иконок, в макете не такая широкая) 
- Перестало работать закрытие попапа персональной странички (при нажатии на иконку персоны раньше открывался попап и было вокруг него затемненное поле по нажатии на который попап закрывался)

#### Что я бы подкорректировал: 
- Если ты уже начал править компанент то проьба убрать комментарии в коде компонентов: `AboutStudioHeader.jsx`, `index.scss`, `UserBar.module.scss`, `Certificate Section.jsx`, 

Будет продолженно...

2024-05-06 08:10 UTC, BRoman22 commented
Привет!

Спасибо за ревью!
Сори что большой ПР, и правда руки чесались исправить многое, в будущем буду работать в рамках задачи.

> * Горизонтальный скрол раньше был скрыт стилями, а это плохая практика.
> * stroke-width поправлю
> * Модалку поправлю, хотя я ее не трогал, предлагаю их вынести из кнопки и из компонента вообще, и в идеале я бы их переписал на порталах.
> * `AboutStudioHeader.jsx`, `UserBar.module.scss`, `Certificate Section.jsx` вносил минорные изменения, все что закоментировано, это до меня так было, `index.scss` - уберу комменты.

Жду следующих комментов :)

2024-05-06 21:15 UTC, zigfrei commented on frontend/public/index.html
> -    <base href="/" />
Я вносил `<base href="/" />` для того чтобы в RCA нормально работал роутинг для динамических роутов, без него он сейчас не рнаботает.

2024-05-06 21:15 UTC, zigfrei commented on frontend/public/manifest.json
Какой смысл его удалять? или превисти в норму или не трогать? Просто его потом все равно придется писать но с нуля.

2024-05-06 21:15 UTC, zigfrei commented on frontend/public/robots.txt
Сайт сейчас не индексируется, но потом все равно придется писать файл роботс.тхт по этому не понимаю зачем его удалять?

2024-05-06 21:15 UTC, zigfrei commented on frontend/src/components/PromoSection/PromoSection.module.scss
> +@media screen and (max-width: 1550px) {
Добавь тогда ширину экрана в глобальные переменные

2024-05-06 21:15 UTC, zigfrei commented on frontend/src/components/PromoSection/PromoSection.module.scss
> +@media screen and (max-width: 1350px) {
Добавь тогда ширину экрана в глобальные переменные

2024-05-06 21:15 UTC, zigfrei commented on frontend/src/components/PromoSection/PromoSection.module.scss
> +@media screen and (max-width: 950px) {
Добавь тогда ширину экрана в глобальные переменные

2024-05-06 21:15 UTC, zigfrei commented on frontend/src/components/PromoSection/PromoSection.module.scss
> +@media screen and (max-width: 1080px) {
Добавь тогда ширину экрана в глобальные переменные

2024-05-06 21:15 UTC, zigfrei commented on frontend/.prettierrc
> +}
Я не в восторге от prettier, мне не нравится когда после сохранения вносятся изменения в код которые я не делал. Еще больше я не в восторге от того чтобы взять и отредактировать сразу 100 файлов... Я пользуюсь линтером, в случае ошибок просто нажимаю устранить все. Ты можешь настроить prettier у себя в расширении чтобы он работал локально? Я бы отказался от него, надо уточнить еще у Риты.

2024-05-06 21:15 UTC, zigfrei commented on frontend/public/index.html
> -    <link rel="apple-touch-icon" href="%PUBLIC_URL%/logo192.png" />
Если уже начал править то приводи к нормальному виду. Добавить полный спектор favicon. 16x16 32x32 svg 120x120 512x512

2024-05-06 21:15 UTC, zigfrei commented on frontend/src/components/AboutStudioHeader/AboutStudioHeader.jsx
>        {/* <div className={cls.route}>
Я понимаю что коментарии не твои, но раз уже начал править компонент то удали лишнее коментарии, все равно никто не помнит зачем они и кто их писал

2024-05-06 21:15 UTC, zigfrei commented on frontend/src/components/App/App.jsx
> +            <Route path={ENDPOINTS.NOT_FOUND} element={<NotFound />} />
Конечно пускай остается, но имхо вредное улучшение, мне чтобы раньше увидеть роут нужно было в один файл посмотреть, теперь мне надо смотреть в два, ну не знаю может для огромных проетков и удобно.

2024-05-06 21:15 UTC, zigfrei commented on frontend/src/components/Atmosphere/Atmosphere.jsx
> +          <img className={cls.image} src={image.link} alt="атмосфера" />
Какой-то альт бесполезный, может поудалять, просто пустым оставить?

2024-05-06 21:15 UTC, zigfrei commented on frontend/src/components/Atmosphere/Atmosphere.jsx
> +        <img className={cls.child1} src={paint} alt="атмосфера" />
Какой-то альт бесполезный, может поудалять, просто пустым оставить?

2024-05-06 21:15 UTC, zigfrei commented on frontend/src/components/CertificateSection/CertificateSection.jsx
>          {/* <h3 className={cls.title}>О сертификате</h3> */}
Убери эти коментарии лишнее

2024-05-06 21:15 UTC, zigfrei commented on frontend/src/components/UserBar/UserBar.module.scss
> +  // после переноса модалки нужно убрать position
Надо убрать коментарии

2024-05-06 21:15 UTC, zigfrei commented on frontend/src/index.scss
> +  // overflow-x: hidden;
Вот из-за этого наверное и вылез скрол

2024-05-06 21:19 UTC, zigfrei commented
> Горизонтальный скрол раньше был скрыт стилями, а это плохая практика.
Горизонтального скрола быть не должно, это и есть плохая практика когда у тебя на странице горизонтальный скрол. Скрыт он был или нет это уже другая задача, которую можно окрыть и разбираться.

2024-05-06 21:21 UTC, zigfrei commented on frontend/public/index.html
> -    <base href="/" />
Или проверить что роутинг работает на всех маршрутах или вернуть

2024-05-06 21:37 UTC, zigfrei commented
Еще расмотри возможность закрытия попапа бургерного меню не только по крестику но и при клике вне поля попапа - это вроде как интуитивное поведение

2024-05-07 07:58 UTC, BRoman22 commented on frontend/public/index.html
> -    <base href="/" />
> Я вносил `<base href="/" />` для того чтобы в RCA нормально работал роутинг для динамических роутов, без него он сейчас не рнаботает.

Можешь пример показать что именно не работает?

2024-05-07 07:59 UTC, BRoman22 commented on frontend/public/manifest.json
Ок, верну пустой файл

2024-05-07 07:59 UTC, BRoman22 commented on frontend/public/robots.txt
Ок, верну пустой файл

2024-05-07 08:02 UTC, BRoman22 commented on frontend/src/components/PromoSection/PromoSection.module.scss
> +@media screen and (max-width: 1550px) {
Правил адаптив хедера, этот компонент еще предстоит править, не вижу смысла исправлять

2024-05-07 08:02 UTC, BRoman22 commented on frontend/src/components/PromoSection/PromoSection.module.scss
> +@media screen and (max-width: 1350px) {
Правил адаптив хедера, этот компонент еще предстоит править, не вижу смысла исправлять

2024-05-07 08:05 UTC, BRoman22 commented on frontend/src/components/Atmosphere/Atmosphere.jsx
> +          <img className={cls.image} src={image.link} alt="атмосфера" />
этот компонент я не трогал, альт до меня был написан, тут лишь автоформатирование сработало на перенос строк

2024-05-07 08:05 UTC, BRoman22 commented on frontend/src/components/Atmosphere/Atmosphere.jsx
> +        <img className={cls.child1} src={paint} alt="атмосфера" />
этот компонент я не трогал, альт до меня был написан, тут лишь автоформатирование сработало на перенос строк

2024-05-07 08:11 UTC, BRoman22 commented on frontend/src/components/CertificateSection/CertificateSection.jsx
>          {/* <h3 className={cls.title}>О сертификате</h3> */}
Не очень понятно 27 строка или законтированный блок кода ниже? Если второе то я не знаю нужно это или нет, это было до меня.
![Снимок экрана 2024-05-07 в 11 08 33](https://github.com/ReneNorth/Mosaic-courses-website/assets/96336622/1b083588-dddb-4db9-83ef-b50a4f16c579)

2024-05-07 08:13 UTC, BRoman22 commented on frontend/src/components/UserBar/UserBar.module.scss
> +  // после переноса модалки нужно убрать position
Вот это я специально оставил чтобы не забыть это сделать, а если даже и забуду, коммент напомнит, можно этот момент вставить в задачу по переносу модалок.

2024-05-07 08:13 UTC, BRoman22 commented on frontend/src/index.scss
> +  // overflow-x: hidden;
100%

2024-05-07 10:10 UTC, RitaKruglova requested changes
**Нужно исправить:**
- Удалить комментарии
- Исправить имена объектов, содержащих константы

2024-05-07 10:10 UTC, RitaKruglova commented on frontend/src/utils/consts/constants.js
> +export const ENDPOINTS = {
Название объектов с константами должно быть в camelCase, а уже сами константы капсом.

2024-05-07 10:10 UTC, RitaKruglova commented on frontend/src/utils/consts/constants.js
> +export const SCREEN_WIDTH = {
То же самое.

2024-05-07 10:10 UTC, RitaKruglova commented on frontend/src/components/CardMoreContent/CardMoreContent.jsx
> +    // eslint-disable-next-line
А зачем здесь отключение eslint?

2024-05-07 10:10 UTC, RitaKruglova commented on frontend/src/components/CertificateSection/CertificateSection.jsx
>          {/* <h3 className={cls.title}>О сертификате</h3> */}
Закомментированный код останется в истории git, так что смело удаляй всё. Если будет нужно, мы его найдем.

2024-05-07 10:10 UTC, RitaKruglova commented on frontend/src/utils/consts/constants.js
> +  // },
Нужно удалить комментрий

2024-05-07 11:58 UTC, BRoman22 commented on frontend/src/components/CardMoreContent/CardMoreContent.jsx
> +    // eslint-disable-next-line
Это была попытка убрать ошибку с лету, но можно добавить задачу убрать все eslint-disable, ошибка была еще до меня

2024-05-07 20:57 UTC, zigfrei reviewed
Замечаний не нашел

2024-05-07 21:39 UTC, merged