Td 266 fix input forms pass
ReneNorth/Mosaic-courses-website pull request #130
Opened 2024-09-07 06:09 UTC by KrisGurach

2024-09-08 17:17 UTC, destren3 commented
Всё отлично

2024-09-09 16:24 UTC, RitaKruglova commented
У нас принято составлять описание пул реквеста: перечислить все изменения и указать ссылку на твою задачу из джиры. Желательно использовать маркдаун. Посмотри оформление моего пул реквеста и сделай по аналогии в следующий раз и отредактируй этот.

2024-09-09 16:53 UTC, RitaKruglova requested changes
Некоторые изменения, которые могут улучшить читабельность кода:
- Имена переменных стоит выбирать более специфические, чтобы читателю было сразу понятно, что лежит в переменной без прочтения всего кода.
- Имена для Boolean должны начинаться с префиксов.
- Убрать лишние скобки.

Проблемы при работе с JSON:
- JSON может быть испорчен и стоит об этом думать, когда мы пытаемся прочитать JSON строки. Всегда стараемся не забывать обрабатывать ошибки, если это возможно.

Рефакторинг:
- Иногда чужой код можно легко улучшить, не стоит этого бояться. Всегда надо стараться сделать код чуточку чище, чем он был до тебя. Даже простое переименование `values` в что-то более специфичное может сильно увеличить читабельность кода.

2024-09-09 16:53 UTC, RitaKruglova commented on frontend/src/components/CheckBoxField/CheckBoxField.jsx
> +        checked={(values && values[CheckBoxSettings[type].name]) || false}
круглые скобки не нужны т.к. логическое "И" и так в приоритете.

2024-09-09 16:53 UTC, RitaKruglova commented on frontend/src/pages/RegisterPage/RegisterPage.jsx
> +            values={values}
По названию переменной `values` непонятно, что там лежат за значения и почему они передаются в каждый элемент. Понимаю, что эта переменная была создана до, но желательно её переименовать во что-то более понятное с первого взгляда. К примеру: `userParameters` или `registrationParameters`, чтобы не нужно было вдумываться в код, а было понятно сразу. В целом в коде лучше избегать "непрозрачных" названий: `value`, `date`, `data` и т.д.

2024-09-09 16:53 UTC, RitaKruglova commented on frontend/src/pages/RegisterPage/RegisterPage.jsx
> +            values={values}
То же самое.)

2024-09-09 16:53 UTC, RitaKruglova commented on frontend/src/pages/RegisterPage/RegisterPage.jsx
> +          {inputError && (<span className={cls.errorMessage}>Пожалуйста, заполните все поля!</span>)}
Здесь снова скобки лишние.

2024-09-09 16:53 UTC, RitaKruglova commented on frontend/src/pages/SignInPage/SignInPage.jsx
> +          {inputError && (<span className={cls.errorMessage}>Пожалуйста, заполните все поля!</span>)}
Скобки снова не нужны.)

2024-09-09 16:53 UTC, RitaKruglova commented on frontend/src/pages/SignInPage/SignInPage.jsx
> +      const allFieldsFilled = values.email && values.password;
Boolean значения лучше называть с префиксов: `are`, `is`, `has`, чтобы всем было очевидно, что это Boolean с первого взгляда. К примеру: `areAllFieldsFilled` - мы как будто бы задаём вопрос.

2024-09-09 16:53 UTC, RitaKruglova commented on frontend/src/pages/RegisterPage/RegisterPage.jsx
> +      const allFieldsFilled = values.email && values.name && values.phone;
Boolean значения лучше называть с префиксов: `are`, `is`, `has`, чтобы всем было очевидно, что это Boolean с первого взгляда. К примеру: `areAllFieldsFilled` - мы как будто бы задаём вопрос.

2024-09-09 16:53 UTC, RitaKruglova commented on frontend/src/pages/RegisterPage/RegisterPage.jsx
> +    const savedValues = JSON.parse(localStorage.getItem(storageKey)) || {};
Не хватает обработки ошибок, JSON может быть испорчен пользователем или нашей неосторожностью. В случае ошибки необходимо установить дефолтное значение `savedValues`.

2024-09-19 05:35 UTC, merged